{
 "title": "K3s Platform Health",
 "description": "Test dashboard.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Demo Web Available Replicas",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"demo\", deployment=\"demo-web\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Demo Web Desired vs Available Replicas",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{\n    namespace=\"demo\",\n    deployment=\"demo-web\"\n  }",
     "legendFormat": "Desired replicas"
    },
    {
     "expr": "kube_deployment_status_replicas_available{\n    namespace=\"demo\",\n    deployment=\"demo-web\"\n  }",
     "legendFormat": "Available replicas"
    }
   ]
  },
  {
   "title": " Ready Cluster Nodes",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Demo Web CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n    rate(\n      container_cpu_usage_seconds_total{\n        namespace=\"demo\",\n        container!=\"\",\n        image!=\"\"\n      }[5m]\n    )\n  )\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Demo Web Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (\n    container_memory_working_set_bytes{\n      namespace=\"demo\",\n      container!=\"\",\n      image!=\"\"\n    }\n  )\n",
     "legendFormat": "{{pods}}"
    }
   ]
  },
  {
   "title": "Demo Web Pod Restarts",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (\n    kube_pod_container_status_restarts_total{\n      namespace=\"demo\"\n    }\n  )",
     "legendFormat": "{{pods}}"
    }
   ]
  }
 ]
}